test: &default

  # Credentials for REST APIs
  client_id: <%= Rails.application.credentials.paypal_client_id %>
  client_secret: <%= Rails.application.credentials.paypal_client_secret %>

  # Mode can be 'live' or 'sandbox'
  mode: sandbox


development:
  <<: *default

production:
  <<: *default
  mode: live
